spring.application.name=springsecurity

# Import .env file - check current directory since it moved to root
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${YOUR_MYSQL_URL}
spring.datasource.username=${YOUR_MYSQL_USERNAME}
spring.datasource.password=${YOUR_MYSQL_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}

